name = "micah/naming"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'micah/naming'"

[repository]
user = "micah"
project = "naming"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
