name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags: ["*.*.*"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Install Aiken
        uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.18-alpha
      - uses: oven-sh/setup-bun@v1
        with:
          registry-url: "https://npm.pkg.github.com/"
          scope: "@foo"
      - name: 📦 Install dependencies
        run: bun i
      - name: 🧪 Run verification
        run: bun run verify
